import {
  BarChart3,
  Building2,
  Download,
  FileText,
  MapPinned,
  UsersRound,
} from "lucide-react";

import PageHeader from "../components/common/PageHeader";

const reports = [
  {
    id: 1,
    title: "State Crime Overview",
    description:
      "Summary of registered cases, crime categories and resolution rates.",
    type: "Analytics",
    icon: BarChart3,
    updated: "Updated today",
  },
  {
    id: 2,
    title: "District Performance Report",
    description:
      "District-wise case volume, resolved cases and police station metrics.",
    type: "District",
    icon: Building2,
    updated: "Updated today",
  },
  {
    id: 3,
    title: "Repeat Offender Intelligence",
    description:
      "Accused persons linked to multiple FIR records and districts.",
    type: "Offender",
    icon: UsersRound,
    updated: "Updated 1 hour ago",
  },
  {
    id: 4,
    title: "Crime Hotspot Assessment",
    description:
      "Geospatial analysis of incident locations and emerging clusters.",
    type: "Geospatial",
    icon: MapPinned,
    updated: "Updated 2 hours ago",
  },
];

function Reports() {
  const downloadReport = (report) => {
    const reportContent = `
KAVACH AI
${report.title}

${report.description}

Generated: ${new Date().toLocaleString()}
Report category: ${report.type}

This is a demonstration report generated by Kavach AI.
Official information must be verified against authorised FIR records.
    `.trim();

    const blob = new Blob([reportContent], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");

    anchor.href = url;
    anchor.download = `${report.title
      .toLowerCase()
      .replaceAll(" ", "-")}.txt`;

    anchor.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex h-full min-h-0 flex-col bg-[#020817]">
      <PageHeader
        icon={FileText}
        title="Reports"
        description="Generate and export operational crime intelligence reports"
      />

      <main className="min-h-0 flex-1 overflow-y-auto p-5">
        <div className="grid gap-5 md:grid-cols-2">
          {reports.map((report) => {
            const Icon = report.icon;

            return (
              <article
                key={report.id}
                className="rounded-2xl border border-slate-700 bg-[#071225] p-5 transition hover:border-blue-500/50"
              >
                <div className="flex items-start gap-4">
                  <div className="rounded-xl bg-blue-500/10 p-3 text-blue-400">
                    <Icon size={23} />
                  </div>

                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center justify-between gap-3">
                      <h2 className="font-semibold text-white">
                        {report.title}
                      </h2>

                      <span className="rounded-full bg-slate-800 px-3 py-1 text-xs text-slate-300">
                        {report.type}
                      </span>
                    </div>

                    <p className="mt-3 text-sm leading-6 text-slate-400">
                      {report.description}
                    </p>

                    <p className="mt-3 text-xs text-slate-500">
                      {report.updated}
                    </p>

                    <button
                      type="button"
                      onClick={() => downloadReport(report)}
                      className="mt-5 flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-blue-500"
                    >
                      <Download size={17} />
                      Generate report
                    </button>
                  </div>
                </div>
              </article>
            );
          })}
        </div>

        <section className="mt-5 rounded-2xl border border-slate-700 bg-[#071225] p-5">
          <h2 className="font-semibold text-white">
            Recent report activity
          </h2>

          <div className="mt-5 overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead>
                <tr className="border-b border-slate-700">
                  <th className="px-4 py-3 text-left text-slate-400">
                    Report
                  </th>
                  <th className="px-4 py-3 text-left text-slate-400">
                    Generated by
                  </th>
                  <th className="px-4 py-3 text-left text-slate-400">
                    Date
                  </th>
                  <th className="px-4 py-3 text-left text-slate-400">
                    Format
                  </th>
                </tr>
              </thead>

              <tbody className="divide-y divide-slate-800">
                <ActivityRow
                  title="Mysuru District Assessment"
                  user="Analyst-22"
                  date="22 Jul 2026, 4:02 PM"
                  format="PDF"
                />
                <ActivityRow
                  title="Repeat Offender Intelligence"
                  user="Investigator-104"
                  date="22 Jul 2026, 3:47 PM"
                  format="PDF"
                />
                <ActivityRow
                  title="Monthly Crime Overview"
                  user="KP-Admin"
                  date="22 Jul 2026, 2:15 PM"
                  format="CSV"
                />
              </tbody>
            </table>
          </div>
        </section>
      </main>
    </div>
  );
}

function ActivityRow({ title, user, date, format }) {
  return (
    <tr>
      <td className="px-4 py-4 font-medium text-white">{title}</td>
      <td className="px-4 py-4 text-slate-300">{user}</td>
      <td className="px-4 py-4 text-slate-400">{date}</td>
      <td className="px-4 py-4">
        <span className="rounded-full bg-blue-500/10 px-3 py-1 text-xs text-blue-400">
          {format}
        </span>
      </td>
    </tr>
  );
}

export default Reports;